routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;


// CLEAR CACHE
Route::prefix('cache')->group(function (){
    Route::get('/config', function () {
        $exit_code = Artisan::call('config:cache');
        return 'true';
    });
    Route::get('/view', function () {
        $exit_code = Artisan::call('view:cache');
        return 'true';
    });
    Route::get('/clear', function () {
        Artisan::call('cache:clear');
        return "Cache is cleared";
    });
});


// API
Route::prefix('Api')->namespace('Api')->name('api.')->group(function() {

    // LOAD BLOG
    Route::post('/loadBlog','BlogController@blogGroups')->name('load.blog');


    // BLOG SEARCH
    Route::post('/Blog/search', 'BlogController@search')->name('blog.search');

    // LIKE AND DISLIKE COMMENT
    Route::post('/Comment/like', 'CommentController@like')->name('comment.like');
    Route::post('/Comment/dislike', 'CommentController@dislike')->name('comment.dislike');


});


// APP
Route::namespace('App')->name('app.')->group(function ()
{
    // HOME
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/page/{page}', 'PageController@show')->name('page.show');

    // SERVICE
    Route::prefix('service')->name('service.')->group(function ()
    {
        Route::get('/show/{service}','ServiceController@show')->name('show');
    });

    // Country
    Route::prefix('country')->name('country.')->group(function ()
    {
        Route::get('/show/{country}','CountryController@show')->name('show');

    });


    // BLOG
    Route::prefix('blog+')->name('blog.')->group(function ()
    {
        Route::get('/{slug?}', 'BlogController@index')->name('home');
        Route::get('/article/{page}', 'BlogController@show')->name('show');
        Route::post('/search', 'BlogController@search')->name('search');
        Route::post('/comment/store', 'CommentController@store')->name('comment.store');
    });

});



// LOGIN ADMIN
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::prefix('admin-panel')->namespace('Auth')->name('admin.')->group(function ()
{
    Route::get('/login', 'AdminController@show')->name('login.show');
    Route::post('/login', 'AdminController@submit')->name('login.submit');

    Route::get('/forget', 'AdminController@forgetform')->name('forget.form');
    Route::post('/forget', 'AdminController@forget')->name('forget');

    Route::get('/reset/{email}', 'AdminController@resetform')->name('reset.form');
    Route::post('/reset', 'AdminController@reset')->name('reset');

    Route::get('logout', 'AdminController@logout')->name('logout');
});



// ADMIN
Route::prefix('admin-panel')->namespace('Admin')->name('admin.')
    ->middleware('auth:admin')->group(function () {


        Route::get('/', 'IndexController@index')->name('dashboard');


        //************ admin  *************
        Route::prefix('admin')->name('admin.')->group(function () {
            Route::get('/edit', 'AdminController@edit')->name('edit');
            Route::put('/update/{user}', 'AdminController@update')->name('update');

            Route::get('/changepassword', 'AdminController@edit_passwrod')->name('edit.password');
            Route::put('/updatepassword', 'AdminController@update_passwrod')->name('update.password');
        });


        //************ user admin *************
        Route::prefix('user')->name('user.')->group(function () {

            Route::get('/list', 'UserController@index')->name('list');

            Route::get('/add', 'UserController@create')->name('create');
            Route::post('/store', 'UserController@store')->name('store');

            Route::get('/edit/{user}', 'UserController@edit')->name('edit');
            Route::post('/update/{user}', 'UserController@update')->name('update');

            Route::get('/show/{user}', 'UserController@show')->name('show');
            Route::post('/search', 'UserController@search')->name('search');
        });


        //************ page admin *************
        Route::prefix('page')->name('page.')->group(function () {
            Route::get('/list', 'PageController@index')->name('list');
            Route::get('/add', 'PageController@create')->name('create');
            Route::post('/store', 'PageController@store')->name('store');
            Route::get('/edit/{page}', 'PageController@edit')->name('edit');
            Route::post('/update/{page}', 'PageController@update')->name('update');
            Route::get('/destroy/{page}', 'PageController@destroy')->name('destroy');
        });


        //************ blog admin *************
        Route::prefix('blog')->name('blog.')->group(function () {
            Route::get('/list', 'BlogController@index')->name('list');
            Route::get('/add', 'BlogController@create')->name('create');
            Route::post('/store', 'BlogController@store')->name('store');
            Route::get('/edit/{page}', 'BlogController@edit')->name('edit');
            Route::post('/update/{page}', 'BlogController@update')->name('update');
            Route::get('/destroy/{page}', 'BlogController@destroy')->name('destroy');
        });


        //************ country admin *************
        Route::prefix('country')->name('country.')->group(function () {
            Route::get('/list', 'CountryController@index')->name('list');
            Route::get('/add', 'CountryController@create')->name('create');
            Route::post('/store', 'CountryController@store')->name('store');
            Route::get('/edit/{country}', 'CountryController@edit')->name('edit');
            Route::post('/update/{country}', 'CountryController@update')->name('update');
            Route::get('/destroy/{country}', 'CountryController@destroy')->name('destroy');
        });


        //************ service admin *************
        Route::prefix('service')->name('service.')->group(function () {
            Route::get('/list', 'ServiceController@index')->name('list');
            Route::get('/add', 'ServiceController@create')->name('create');
            Route::post('/store', 'ServiceController@store')->name('store');
            Route::get('/edit/{service}', 'ServiceController@edit')->name('edit');
            Route::post('/update/{service}', 'ServiceController@update')->name('update');
            Route::get('/destroy/{service}', 'ServiceController@destroy')->name('destroy');
        });


        //************ category admin *************
        Route::prefix('category')->name('category.')->group(function () {
            Route::get('/list/{type}', 'CategoryController@index')->name('list');
            Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
            Route::post('/update/{id}', 'CategoryController@update')->name('update');
            Route::post('/add', 'CategoryController@store')->name('store');
            Route::get('/destroy/{id}', 'CategoryController@destroy')->name('destroy');
        });


        //************ setting admin *************
        Route::name('setting.')->group(function () {
            Route::get('/setting', 'SettingController@edit')->name('edit');
            Route::post('/setting', 'SettingController@update')->name('update');
        });


        // ****************** social ***********
        Route::prefix('social')->name('social.')->group(function() {
            Route::get('list', 'SocialController@index')->name('list');
            Route::post('store', 'SocialController@store')->name('store');
            Route::get('destroy/{meta}', 'SocialController@destroy')->name('destroy');
        });


        //************ about admin *************
        Route::prefix('aboutus')->name('aboutus.')->group(function () {
            Route::get('/aboutus', 'AboutController@index')->name('list');
            Route::post('/aboutus/store', 'AboutController@store')->name('store');
            Route::get('/aboutus/destroy/{id}', 'AboutController@destroy')->name('destroy');
        });


        //************ service admin *************
        Route::prefix('menu')->name('menu.')->group(function () {
            Route::get('/list', 'MenuController@index')->name('list');
            Route::post('/store', 'MenuController@store')->name('store');
            Route::get('/edit/{menu}', 'MenuController@edit')->name('edit');
            Route::post('/update/{menu}', 'MenuController@update')->name('update');
            Route::get('/destroy/{menu}', 'MenuController@destroy')->name('destroy');
        });

        //************ image admin *************
        Route::prefix('image')->name('image.')->group(function() {
            Route::get('list', 'ImageController@index')->name('list');
            Route::post('store', 'ImageController@store')->name('store');
            Route::get('edit/{image}', 'ImageController@edit')->name('edit');
            Route::post('update/{image}', 'ImageController@update')->name('update');
            Route::get('destroy/{image}', 'ImageController@destroy')->name('destroy');
        });


    });

// FILE MANAGER
Route::group(['prefix' => 'filemanager', 'middleware' => ['web', 'auth:admin']], function () {
    Lfm::routes();
});

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    protected $fillable = ['title','url','position','parent'];

    public $timestamps = false;

    public function Child()
    {
        return $this->hasMany('App\Models\Menu','parent','id');
    }
}

app/Http/Controllers/Admin/MenuController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Menu;
use App\Models\Setting;
use Illuminate\Http\Request;

class MenuController extends BasicController
{



    public function index()
   {
       $response = $this->AdminVariable();

       $response['menu'] = Menu::orderBy('id','ASC')->paginate(15);
       $response['parent'] = Menu::orderBy('title','ASC')->get();

       return view('admin.page.menu.list',compact('response'));
   }

    public function store(Request $request)
    {
        $request->validate(['title'=>'required']);

        $menu = new Menu();
        $menu->title     = $request->title;
        $menu->url       = $request->url;
        $menu->position  = $request->position;
        $menu->parent    = $request->parent;

        try{
            $menu->save();
        }
        catch (Exception $exception)
        {
            return redirect()->back()->with('warning',$exception->getCode());
        }

        return redirect()->back()->with('success','عملیات با موفقیت انجام شد.');

    }

    public function edit(Menu $menu)
    {
        $response = $this->AdminVariable();

        $response['menu']=$menu;
        $response['parent'] = Menu::where('id','<>',$menu->id)->orderBy('title','ASC')->get();

        return view('admin.page.menu.edit',compact('response'));
    }

    public function update(Request $request,Menu $menu)
    {
        $request->validate(['title'=>'required']);

        $menu->title     = $request->title;
        $menu->url       = $request->url;
        $menu->position  = $request->position;
        $menu->parent    = $request->parent;

        try{
            $menu->save();
        }
        catch (Exception $exception)
        {
            return redirect()->back()->with('warning',$exception->getCode());
        }

        return redirect()->back()->with('success','عملیات با موفقیت انجام شد.');
    }

    public function destroy(Menu $menu)
    {
        $menu->delete();
        return redirect()->back()->with('success','عملیات با موفقیت انجام شد.');
    }


}

resources/views/admin/page/menu/edit.blade.php
@extends('admin.index')

@section('breadCrumb')
    {{ \DaveJamesMiller\Breadcrumbs\Facades\Breadcrumbs::render('admin.menu.edit',$response['menu']) }}
@endsection


@section('content')
    <section class="direction-ltr bg-white pt-0">
        <div class="container-fluid my-5">
            <form  action="{{route('admin.menu.update',$response['menu']->id)}}" method="POST" class="form admin-form">
                @csrf

                <div class="form-row mt-3">
                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mx-auto mb-4">
                        <label for="title_id" class="admin-input-label"><i class="fas fa-pencil-alt prefix text-right"></i>&nbsp;عنوان</label>
                        <input type="text" autocomplete="off" class="form-control admin-input @error('title') is-invalid @enderror"
                               id="title_id" name="title" placeholder="عنوان" value="{{$response['menu']->title}}">
                    </div>

                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mx-auto mb-4">
                        <label for="url" class="admin-input-label"><i class="fas fa-pencil-alt prefix text-right"></i>&nbsp;آدرس صفحه ای که کاربر با کلیک منتقل میگردد</label>
                        <input type="text" autocomplete="off" class="form-control admin-input"
                               id="url" name="url" placeholder="آدرس صفحه ای که کاربر با کلیک منتقل میگردد"
                               value="{{$response['menu']->url}}">
                    </div>

                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mx-auto mb-4">
                        <label for="parent" class="admin-input-label"><i class="fas fa-pencil-alt prefix text-right"></i>&nbsp;انتخاب والد</label>

                        <select class="form-control admin-input" id="parent" name="parent">
                            <option class="admin-input" value="" {{$response['menu']->parent == '' ? 'selected' : ''}}>سرگروه</option>
                            @foreach($response['parent'] as $parent)
                                <option class="admin-input" value="{{$parent->id}}"
                                    {{$parent->id === $response['menu']->parent ? 'selected' : ''}}>{{$parent->title}}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mx-auto mb-4">
                        <label for="position" class="admin-input-label"><i class="fas fa-pencil-alt prefix text-right"></i>&nbsp;محل قرارگیری</label>
                        <select class="form-control admin-input" id="position" name="position">
                            <option class="admin-input" value="top" {{$response['menu']->position === 'top' ? 'selected' : ''}}>بالا</option>
                            <option class="admin-input" value="bottom" {{$response['menu']->position === 'bottom' ? 'selected' : ''}}>پایین</option>
                            <option class="admin-input" value="both" {{$response['menu']->position === 'both' ? 'selected' : ''}}>بالا و پایین</option>
                        </select>
                    </div>

                </div>
                <div class="form-row my-4">
                    <input type="submit" class="col-xl-4 col-lg-4 col-md-8 col-sm-10 col-xs-10 btn admin-submit" value="ویرایش اطلاعات" >
                </div>
            </form>
        </div>
    </section>
@endsection

resources/views/admin/page/menu/list.blade.php
@extends('admin.index')

@section('breadCrumb')
    {{ \DaveJamesMiller\Breadcrumbs\Facades\Breadcrumbs::render('admin.menu.list') }}
@endsection


@section('content')
    @include('message.message')

    <div class="table-responsive admin-div-table">
        <table class="table table-striped table-bordered">
            <tr class="admin-table-hr-row">
                <td class="font-size-13">ردیف</td>
                <td class="font-size-13">عنوان</td>
                <td class="font-size-13">آدرس</td>
                <td class="font-size-13">والد</td>
                <td class="font-size-13">جایگاه</td>
                <td class="font-size-13">تنظیمات</td>
            </tr>
            <tbody id="menu_table">
            @foreach($response['menu'] as $row => $menu)
                <tr class="text-center">

                    <td class="admin-danger">{{++$row}}</td>

                    <td class="admin-black">{{$menu->title}}</td>

                    <td>
                        @if($menu->url != null)
                            <a class="text-decoration-none admin-secondary" href="{{$menu->url}}">{{$menu->url}}</a>
                        @else
                            <span class="admin-danger">تعـریف نشده</span>
                        @endif
                    </td>

                    <td class="admin-black">{{$menu->parent != null ? optional($menu->Parent)->title : 'سـرگروه'}}</td>

                    <td class="admin-info">
                        @switch($menu->position)
                            @case('top')
                            بالا
                            @break
                            @case('bottom')
                            پایین
                            @break
                            @case('both')
                            بالا و پایین
                            @break
                        @endswitch
                    </td>
                    <td>
                        <a href="{{route('admin.menu.edit',$menu->id)}}"
                           class="btn btn-outline-primary btn-sm admin-a">
                            ویرایش
                        </a>
                        <a href="{{route('admin.menu.destroy',$menu->id)}}"
                           class="btn btn-outline-danger btn-sm admin-a">
                            حذف
                        </a>
                    </td>

                </tr>
            @endforeach
            </tbody>
        </table>
        {{$response['menu']->links()}}
    </div>

    <section class="direction-ltr bg-white pt-0">
        <div class="container-fluid my-5">
            <form action="{{route('admin.menu.store')}}" method="POST" class="form admin-form">
                @csrf

                <div class="form-row mt-3">
                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mx-auto mb-4">
                        <label for="title_id" class="admin-input-label"><i
                                class="fas fa-pencil-alt prefix text-right"></i>&nbsp;عنوان</label>
                        <input type="text" autocomplete="off"
                               class="form-control admin-input @error('title') is-invalid @enderror" id="title_id"
                               name="title" placeholder="عنوان" value="{{old('title')}}">
                    </div>

                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mx-auto mb-4">
                        <label for="url" class="admin-input-label"><i class="fas fa-pencil-alt prefix text-right"></i>&nbsp;آدرس
                            صفحه ای که کاربر با کلیک منتقل میگردد</label>
                        <input type="text" autocomplete="off" class="form-control admin-input" id="url" name="url"
                               placeholder="آدرس صفحه ای که کاربر با کلیک منتقل میگردد" value="{{old('url')}}">
                    </div>

                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mx-auto mb-4">
                        <label for="parent" class="admin-input-label"><i
                                class="fas fa-pencil-alt prefix text-right"></i>&nbsp;انتخاب والد</label>

                        <select class="form-control admin-input" id="parent" name="parent">
                            <option class="admin-input" value="">سرگروه</option>
                            @foreach($response['parent'] as $parent)
                                <option class="admin-input" value="{{$parent->id}}">{{$parent->title}}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mx-auto mb-4">
                        <label for="position" class="admin-input-label"><i
                                class="fas fa-pencil-alt prefix text-right"></i>&nbsp;محل قرارگیری</label>
                        <select class="form-control admin-input" id="position" name="position">
                            <option class="admin-input" value="top">بالا</option>
                            <option class="admin-input" value="bottom">پایین</option>
                            <option class="admin-input" value="both">بالا و پایین</option>
                        </select>
                    </div>

                </div>
                <div class="form-row my-4">
                    <input type="submit" class="col-xl-4 col-lg-4 col-md-8 col-sm-10 col-xs-10 btn admin-submit"
                           value="افزودن">
                </div>
            </form>
        </div>
    </section>

@endsection


@section('script')
    <script type="text/javascript">
        let data = [
                @foreach($response['menu'] as $row => $menu)
            {
                row: '{{$row}}',
                id: '{{$menu->id}}',
                title: '{{$menu->title}}',
                url: '{{$menu->url}}',
                parent: '{{$menu->parent != null ? optional($menu->Parent)->title : 'سـرگروه'}}'
            },
            @endforeach
        ]

        new DragAndDrop(
            {
                el: document.querySelector('#menu_table'),
                list: data,
                template: (item) => {
                    return  `<tr id="${item.id}" class="text-center menu-item" >
                                <td class="admin-danger">${++item.row}</td>
                                <td class="admin-black">${item.title}</td>
                                <td><a class="text-decoration-none admin-secondary" href="${item.url}">${item.url}</a></td>
                                <td class="admin-black">${item.parent}</td>
                                <td><a href="" class="btn btn-outline-primary btn-sm admin-a"> ویرایش</a></td>
                                <td><a href="" class="btn btn-outline-danger btn-sm admin-a"> حذف</a></td>
                             </tr> `;
                }
            })
    </script>
@endsection