routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;


// CLEAR CACHE
Route::prefix('cache')->group(function (){
    Route::get('/config', function () {
        $exit_code = Artisan::call('config:cache');
        return 'true';
    });
    Route::get('/view', function () {
        $exit_code = Artisan::call('view:cache');
        return 'true';
    });
    Route::get('/clear', function () {
        Artisan::call('cache:clear');
        return "Cache is cleared";
    });
});


// API
Route::prefix('Api')->namespace('Api')->name('api.')->group(function() {

    // LOAD BLOG
    Route::post('/loadBlog','BlogController@blogGroups')->name('load.blog');


    // BLOG SEARCH
    Route::post('/Blog/search', 'BlogController@search')->name('blog.search');

    // LIKE AND DISLIKE COMMENT
    Route::post('/Comment/like', 'CommentController@like')->name('comment.like');
    Route::post('/Comment/dislike', 'CommentController@dislike')->name('comment.dislike');


});


// APP
Route::namespace('App')->name('app.')->group(function ()
{
    // HOME
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/page/{page}', 'PageController@show')->name('page.show');

    // SERVICE
    Route::prefix('service')->name('service.')->group(function ()
    {
        Route::get('/show/{service}','ServiceController@show')->name('show');
    });

    // Country
    Route::prefix('country')->name('country.')->group(function ()
    {
        Route::get('/show/{country}','CountryController@show')->name('show');

    });


    // BLOG
    Route::prefix('blog+')->name('blog.')->group(function ()
    {
        Route::get('/{slug?}', 'BlogController@index')->name('home');
        Route::get('/article/{page}', 'BlogController@show')->name('show');
        Route::post('/search', 'BlogController@search')->name('search');
        Route::post('/comment/store', 'CommentController@store')->name('comment.store');
    });

});



// LOGIN ADMIN
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::prefix('admin-panel')->namespace('Auth')->name('admin.')->group(function ()
{
    Route::get('/login', 'AdminController@show')->name('login.show');
    Route::post('/login', 'AdminController@submit')->name('login.submit');

    Route::get('/forget', 'AdminController@forgetform')->name('forget.form');
    Route::post('/forget', 'AdminController@forget')->name('forget');

    Route::get('/reset/{email}', 'AdminController@resetform')->name('reset.form');
    Route::post('/reset', 'AdminController@reset')->name('reset');

    Route::get('logout', 'AdminController@logout')->name('logout');
});



// ADMIN
Route::prefix('admin-panel')->namespace('Admin')->name('admin.')
    ->middleware('auth:admin')->group(function () {


        Route::get('/', 'IndexController@index')->name('dashboard');


        //************ admin  *************
        Route::prefix('admin')->name('admin.')->group(function () {
            Route::get('/edit', 'AdminController@edit')->name('edit');
            Route::put('/update/{user}', 'AdminController@update')->name('update');

            Route::get('/changepassword', 'AdminController@edit_passwrod')->name('edit.password');
            Route::put('/updatepassword', 'AdminController@update_passwrod')->name('update.password');
        });


        //************ user admin *************
        Route::prefix('user')->name('user.')->group(function () {

            Route::get('/list', 'UserController@index')->name('list');

            Route::get('/add', 'UserController@create')->name('create');
            Route::post('/store', 'UserController@store')->name('store');

            Route::get('/edit/{user}', 'UserController@edit')->name('edit');
            Route::post('/update/{user}', 'UserController@update')->name('update');

            Route::get('/show/{user}', 'UserController@show')->name('show');
            Route::post('/search', 'UserController@search')->name('search');
        });


        //************ page admin *************
        Route::prefix('page')->name('page.')->group(function () {
            Route::get('/list', 'PageController@index')->name('list');
            Route::get('/add', 'PageController@create')->name('create');
            Route::post('/store', 'PageController@store')->name('store');
            Route::get('/edit/{page}', 'PageController@edit')->name('edit');
            Route::post('/update/{page}', 'PageController@update')->name('update');
            Route::get('/destroy/{page}', 'PageController@destroy')->name('destroy');
        });


        //************ blog admin *************
        Route::prefix('blog')->name('blog.')->group(function () {
            Route::get('/list', 'BlogController@index')->name('list');
            Route::get('/add', 'BlogController@create')->name('create');
            Route::post('/store', 'BlogController@store')->name('store');
            Route::get('/edit/{page}', 'BlogController@edit')->name('edit');
            Route::post('/update/{page}', 'BlogController@update')->name('update');
            Route::get('/destroy/{page}', 'BlogController@destroy')->name('destroy');
        });


        //************ country admin *************
        Route::prefix('country')->name('country.')->group(function () {
            Route::get('/list', 'CountryController@index')->name('list');
            Route::get('/add', 'CountryController@create')->name('create');
            Route::post('/store', 'CountryController@store')->name('store');
            Route::get('/edit/{country}', 'CountryController@edit')->name('edit');
            Route::post('/update/{country}', 'CountryController@update')->name('update');
            Route::get('/destroy/{country}', 'CountryController@destroy')->name('destroy');
        });


        //************ service admin *************
        Route::prefix('service')->name('service.')->group(function () {
            Route::get('/list', 'ServiceController@index')->name('list');
            Route::get('/add', 'ServiceController@create')->name('create');
            Route::post('/store', 'ServiceController@store')->name('store');
            Route::get('/edit/{service}', 'ServiceController@edit')->name('edit');
            Route::post('/update/{service}', 'ServiceController@update')->name('update');
            Route::get('/destroy/{service}', 'ServiceController@destroy')->name('destroy');
        });


        //************ category admin *************
        Route::prefix('category')->name('category.')->group(function () {
            Route::get('/list/{type}', 'CategoryController@index')->name('list');
            Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
            Route::post('/update/{id}', 'CategoryController@update')->name('update');
            Route::post('/add', 'CategoryController@store')->name('store');
            Route::get('/destroy/{id}', 'CategoryController@destroy')->name('destroy');
        });


        //************ setting admin *************
        Route::name('setting.')->group(function () {
            Route::get('/setting', 'SettingController@edit')->name('edit');
            Route::post('/setting', 'SettingController@update')->name('update');
        });


        // ****************** social ***********
        Route::prefix('social')->name('social.')->group(function() {
            Route::get('list', 'SocialController@index')->name('list');
            Route::post('store', 'SocialController@store')->name('store');
            Route::get('destroy/{meta}', 'SocialController@destroy')->name('destroy');
        });


        //************ about admin *************
        Route::prefix('aboutus')->name('aboutus.')->group(function () {
            Route::get('/aboutus', 'AboutController@index')->name('list');
            Route::post('/aboutus/store', 'AboutController@store')->name('store');
            Route::get('/aboutus/destroy/{id}', 'AboutController@destroy')->name('destroy');
        });


        //************ service admin *************
        Route::prefix('menu')->name('menu.')->group(function () {
            Route::get('/list', 'MenuController@index')->name('list');
            Route::post('/store', 'MenuController@store')->name('store');
            Route::get('/edit/{menu}', 'MenuController@edit')->name('edit');
            Route::post('/update/{menu}', 'MenuController@update')->name('update');
            Route::get('/destroy/{menu}', 'MenuController@destroy')->name('destroy');
        });

        //************ image admin *************
        Route::prefix('image')->name('image.')->group(function() {
            Route::get('list', 'ImageController@index')->name('list');
            Route::post('store', 'ImageController@store')->name('store');
            Route::get('edit/{image}', 'ImageController@edit')->name('edit');
            Route::post('update/{image}', 'ImageController@update')->name('update');
            Route::get('destroy/{image}', 'ImageController@destroy')->name('destroy');
        });


    });

// FILE MANAGER
Route::group(['prefix' => 'filemanager', 'middleware' => ['web', 'auth:admin']], function () {
    Lfm::routes();
});

app/Models/Image.php
<?php

namespace App\Models;

use App\Traits\HasFile;
use App\Traits\HasMeta;
use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    use HasMeta;

    protected $fillable = ['src','url','title','key'];

    protected $casts = ['src'=>'array'];

    public $timestamps = false;


    public function Parent()
    {
        return $this->belongsTo('App\Models\Setting','key','key');
    }
}

app/Http/Controllers/Admin/ImageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Image;
use App\Models\Setting;
use Illuminate\Http\Request;

class ImageController extends BasicController
{

    public function index()
    {
        $response = $this->AdminVariable();
        $response['image']  = Image::orderBy('key','ASC')->paginate(15);
        $response['parent'] = Setting::where('type','image')->get();
        return view('admin.page.image.list',compact('response'));
    }


    public function store(Request $request)
    {
        $request->validate([
            'image'=>'required|image|max:2048',
            'title'=>'required',
        ]);


        $parent = Setting::firstWhere('key',$request->parent);

        // UPDATE LOGO TO STORAGE/SETTING
        if ($request->hasFile('image'))
        {
            $imageUrl = $this->uploadImage($request->file('image'),'image',[$parent->value]);
        }

        $image             = new Image();
        $image->src        = $imageUrl;
        $image->title      = $request->title;
        $image->url        = $request->url;
        $image->key        = $parent->key;

        $image->save();

        return redirect()->back()->with('success', 'عملیات با موفقیت انجام شد.');
    }

    public function edit(Image $image)
    {
        $response = $this->AdminVariable();
        $response['image']  = $image;
        $response['parent'] = Setting::where('type','image')->get();

        return view('admin.page.image.edit',compact('response'));
    }

    public function update(Request $request,Image $image)
    {
        $request->validate(['title'=>'required']);

        $parent = Setting::firstWhere('key',$request->parent);

        // UPDATE LOGO TO STORAGE/SETTING
        if ($request->hasFile('image'))
        {
            $imageUrl = $this->uploadImage($request->file('image'),'image',[$parent->value]);
            $image->src   = $imageUrl;

        }

        $image->title = $request->title;
        $image->key   = $parent->key;
        $image->url   = $request->url;

        $image->save();

        return redirect()->back()->with('success', 'عملیات با موفقیت انجام شد.');
    }

    public function destroy(Image $image)
    {
        try
        {
            $image->delete();
        }
        catch (Exception $exception)
        {
            return redirect()->back()->with('warning', $exception->getCode());
        }
        return redirect()->back()->with('success', 'عملیات با موفقیت انجام شد.');

    }
}

resources/views/admin/page/image/edit.blade.php
@extends('admin.index')

@section('breadCrumb')
    {{ \DaveJamesMiller\Breadcrumbs\Facades\Breadcrumbs::render('admin.image.edit',$response['image']) }}
@endsection


@section('content')

    <section class="bg-white pt-0" id="welcome">
        <div class="container-fluid my-5">
            @include('message.message')
            <form action="{{route('admin.image.update',$response['image']->id)}}"
                  method="POST" enctype="multipart/form-data"
                  class="form admin-form">
                @csrf


                <div class="form-row mb-3 p-3">
                    <div class="align-right mr-2">
                        <div class="image-upload">
                            <label for="image">
                                <span class="admin-input-label d-block">انتخاب تصویر</span>
                                <img src="{{isset($response['image']->src[$response['image']->Parent->value]) ? url($response['image']->src[$response['image']->Parent->value]): url('/app/img/image-add-button.png') }}" id="preview"
                                     class="img-thumbnail admin-form-img"/>
                            </label>
                            <input type="file" name="image" id="image" onchange="readURL(this);"
                                   class="d-none">
                        </div>
                    </div>
                </div>

                <div class="form-row mt-3">
                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mb-4">
                        <label for="title_id" class="admin-input-label">
                            <i class="fas fa-pencil-alt prefix text-right"></i>
                            عنوان
                        </label>
                        <input type="text" class="form-control admin-input @error('title') is-invalid @enderror"
                               id="title_id" name="title" placeholder="عنوان"
                                value="{{$response['image']->title}}">
                    </div>

                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mb-4">
                        <label for="url" class="admin-input-label">
                            <i class="fas fa-pencil-alt prefix text-right"></i>
                            آدرس انتقال کاربر هنگام کلیک روی تصویر
                        </label>
                        <input type="text" class="form-control admin-input"
                               id="url" name="url" placeholder="آدرس انتقال کاربر هنگام کلیک روی تصویر"
                                value="{{$response['image']->url}}">
                    </div>

                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mb-4">
                        <label for="parent" class="admin-input-label">
                            <i class="fas fa-pencil-alt prefix text-right"></i>
                            والد
                        </label>
                        <select class="form-control admin-input" name="parent" id="parent">
                            @foreach($response['parent'] as $parent)
                                <option value="{{$parent->key}}"
                                    {{$parent->key === $response['image']->key ? 'selected' : ''}}>
                                    {{$parent->title}}
                                    ({{$parent->value}})
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="form-row my-4">
                    <input type="submit" class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12 btn admin-submit"
                           value="ویرایش کردن">
                </div>
            </form>
        </div>

    </section>


@endsection

@section('script')
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#preview').attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
@endsection

resources/views/admin/page/image/list.blade.php
@extends('admin.index')

@section('breadCrumb')
    {{ \DaveJamesMiller\Breadcrumbs\Facades\Breadcrumbs::render('admin.image.list') }}
@endsection


@section('content')

    <section class="bg-white pt-0" id="welcome">

        <div class="table-responsive admin-div-table">
            <table class="table table-striped table-bordered">
                <tr class="admin-table-hr-row">
                    <td class="font-size-13">ردیف</td>
                    <td class="font-size-13">تصویر</td>
                    <td class="font-size-13">عنوان</td>
                    <td class="font-size-13">آدرس</td>
                    <td class="font-size-13">بخش</td>
                    <td class="font-size-13">تنظیمات</td>
                </tr>
                <tbody>
                @foreach($response['image'] as $row => $image)
                    <tr class="text-center font-size-14">
                        <td class="admin-danger pt-4">{{++$row}}</td>
                        <td>
                            <img src="{{url($image->src[$image->Parent->value])}}" class="admin-table-img img-thumbnail">
                        </td>
                        <td class="admin-black pt-4">
                            {{$image->title}}
                        </td>
                        <td class="pt-4">
                            <a href="{{$image->url}}" class="text-decoration-none admin-info">
                                {{$image->url}}
                            </a>
                        </td>
                        <td class="admin-success pt-4">
                            {{$image->Parent->title}}
                        </td>
                        <td>
                            <a href="{{route('admin.image.edit',$image->id)}}"
                               class="btn btn-outline-info btn-sm font-yekan mt-2">
                                ویرایش
                            </a>
                            <a href="{{route('admin.image.destroy',$image->id)}}"
                               class="btn btn-outline-danger btn-sm font-yekan mt-2">
                                حذف
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

        <div class="container-fluid my-5">
            @include('message.message')
            <form action="{{route('admin.image.store')}}"
                  method="POST" enctype="multipart/form-data"
                  class="form admin-form">
                @csrf
                <div class="form-row mb-3 p-3">
                    <div class="align-right mr-2">
                        <div class="image-upload">
                            <label for="image">
                                <span class="admin-input-label d-block">انتخاب تصویر</span>
                                <img src="{{url('/app/img/image-add-button.png')}}" id="preview"
                                     class="img-thumbnail mt-2"
                                     height="100px" width="100px" style="border: 1px dashed #cecece"/>
                            </label>

                            <input type="file" name="image" id="image" onchange="readURL(this);"
                                   class="d-none">
                        </div>
                    </div>
                </div>

                <div class="form-row mt-3">
                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mb-4">
                        <label for="title_id" class="admin-input-label">
                            <i class="fas fa-pencil-alt prefix text-right"></i>
                            عنوان
                        </label>
                        <input type="text" class="form-control admin-input @error('title') is-invalid @enderror"
                               id="title_id" name="title" placeholder=" عنوان ">
                    </div>

                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mb-4">
                        <label for="url" class="admin-input-label">
                            <i class="fas fa-pencil-alt prefix text-right"></i>
                            آدرس انتقال کاربر هنگام کلیک روی تصویر
                        </label>
                        <input type="text" class="form-control admin-input"
                               id="url" name="url" placeholder="  آدرس انتقال کاربر هنگام کلیک روی تصویر ">
                    </div>

                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 mb-4">
                        <label for="parent" class="admin-input-label">
                            <i class="fas fa-pencil-alt prefix text-right"></i>
                            والد
                        </label>
                        <select class="form-control admin-input" name="parent" id="parent">
                            @foreach($response['parent'] as $parent)
                                <option value="{{$parent->key}}">
                                    {{$parent->title}}
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="form-row my-4">
                    <input type="submit" class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12 btn admin-submit"
                           value="اضافه کردن">
                </div>
            </form>
        </div>

    </section>


@endsection

@section('script')
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#preview').attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
@endsection