routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;


// CLEAR CACHE
Route::prefix('cache')->group(function (){
    Route::get('/config', function () {
        $exit_code = Artisan::call('config:cache');
        return 'true';
    });
    Route::get('/view', function () {
        $exit_code = Artisan::call('view:cache');
        return 'true';
    });
    Route::get('/clear', function () {
        Artisan::call('cache:clear');
        return "Cache is cleared";
    });
});


// API
Route::prefix('Api')->namespace('Api')->name('api.')->group(function() {

    // LOAD BLOG
    Route::post('/loadBlog','BlogController@blogGroups')->name('load.blog');


    // BLOG SEARCH
    Route::post('/Blog/search', 'BlogController@search')->name('blog.search');

    // LIKE AND DISLIKE COMMENT
    Route::post('/Comment/like', 'CommentController@like')->name('comment.like');
    Route::post('/Comment/dislike', 'CommentController@dislike')->name('comment.dislike');


});


// APP
Route::namespace('App')->name('app.')->group(function ()
{
    // HOME
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/page/{page}', 'PageController@show')->name('page.show');

    // SERVICE
    Route::prefix('service')->name('service.')->group(function ()
    {
        Route::get('/show/{service}','ServiceController@show')->name('show');
    });

    // Country
    Route::prefix('country')->name('country.')->group(function ()
    {
        Route::get('/show/{country}','CountryController@show')->name('show');

    });


    // BLOG
    Route::prefix('blog+')->name('blog.')->group(function ()
    {
        Route::get('/{slug?}', 'BlogController@index')->name('home');
        Route::get('/article/{page}', 'BlogController@show')->name('show');
        Route::post('/search', 'BlogController@search')->name('search');
        Route::post('/comment/store', 'CommentController@store')->name('comment.store');
    });

});



// LOGIN ADMIN
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::prefix('admin-panel')->namespace('Auth')->name('admin.')->group(function ()
{
    Route::get('/login', 'AdminController@show')->name('login.show');
    Route::post('/login', 'AdminController@submit')->name('login.submit');

    Route::get('/forget', 'AdminController@forgetform')->name('forget.form');
    Route::post('/forget', 'AdminController@forget')->name('forget');

    Route::get('/reset/{email}', 'AdminController@resetform')->name('reset.form');
    Route::post('/reset', 'AdminController@reset')->name('reset');

    Route::get('logout', 'AdminController@logout')->name('logout');
});



// ADMIN
Route::prefix('admin-panel')->namespace('Admin')->name('admin.')
    ->middleware('auth:admin')->group(function () {


        Route::get('/', 'IndexController@index')->name('dashboard');


        //************ admin  *************
        Route::prefix('admin')->name('admin.')->group(function () {
            Route::get('/edit', 'AdminController@edit')->name('edit');
            Route::put('/update/{user}', 'AdminController@update')->name('update');

            Route::get('/changepassword', 'AdminController@edit_passwrod')->name('edit.password');
            Route::put('/updatepassword', 'AdminController@update_passwrod')->name('update.password');
        });


        //************ user admin *************
        Route::prefix('user')->name('user.')->group(function () {

            Route::get('/list', 'UserController@index')->name('list');

            Route::get('/add', 'UserController@create')->name('create');
            Route::post('/store', 'UserController@store')->name('store');

            Route::get('/edit/{user}', 'UserController@edit')->name('edit');
            Route::post('/update/{user}', 'UserController@update')->name('update');

            Route::get('/show/{user}', 'UserController@show')->name('show');
            Route::post('/search', 'UserController@search')->name('search');
        });


        //************ page admin *************
        Route::prefix('page')->name('page.')->group(function () {
            Route::get('/list', 'PageController@index')->name('list');
            Route::get('/add', 'PageController@create')->name('create');
            Route::post('/store', 'PageController@store')->name('store');
            Route::get('/edit/{page}', 'PageController@edit')->name('edit');
            Route::post('/update/{page}', 'PageController@update')->name('update');
            Route::get('/destroy/{page}', 'PageController@destroy')->name('destroy');
        });


        //************ blog admin *************
        Route::prefix('blog')->name('blog.')->group(function () {
            Route::get('/list', 'BlogController@index')->name('list');
            Route::get('/add', 'BlogController@create')->name('create');
            Route::post('/store', 'BlogController@store')->name('store');
            Route::get('/edit/{page}', 'BlogController@edit')->name('edit');
            Route::post('/update/{page}', 'BlogController@update')->name('update');
            Route::get('/destroy/{page}', 'BlogController@destroy')->name('destroy');
        });


        //************ country admin *************
        Route::prefix('country')->name('country.')->group(function () {
            Route::get('/list', 'CountryController@index')->name('list');
            Route::get('/add', 'CountryController@create')->name('create');
            Route::post('/store', 'CountryController@store')->name('store');
            Route::get('/edit/{country}', 'CountryController@edit')->name('edit');
            Route::post('/update/{country}', 'CountryController@update')->name('update');
            Route::get('/destroy/{country}', 'CountryController@destroy')->name('destroy');
        });


        //************ service admin *************
        Route::prefix('service')->name('service.')->group(function () {
            Route::get('/list', 'ServiceController@index')->name('list');
            Route::get('/add', 'ServiceController@create')->name('create');
            Route::post('/store', 'ServiceController@store')->name('store');
            Route::get('/edit/{service}', 'ServiceController@edit')->name('edit');
            Route::post('/update/{service}', 'ServiceController@update')->name('update');
            Route::get('/destroy/{service}', 'ServiceController@destroy')->name('destroy');
        });


        //************ category admin *************
        Route::prefix('category')->name('category.')->group(function () {
            Route::get('/list/{type}', 'CategoryController@index')->name('list');
            Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
            Route::post('/update/{id}', 'CategoryController@update')->name('update');
            Route::post('/add', 'CategoryController@store')->name('store');
            Route::get('/destroy/{id}', 'CategoryController@destroy')->name('destroy');
        });


        //************ setting admin *************
        Route::name('setting.')->group(function () {
            Route::get('/setting', 'SettingController@edit')->name('edit');
            Route::post('/setting', 'SettingController@update')->name('update');
        });


        // ****************** social ***********
        Route::prefix('social')->name('social.')->group(function() {
            Route::get('list', 'SocialController@index')->name('list');
            Route::post('store', 'SocialController@store')->name('store');
            Route::get('destroy/{meta}', 'SocialController@destroy')->name('destroy');
        });


        //************ about admin *************
        Route::prefix('aboutus')->name('aboutus.')->group(function () {
            Route::get('/aboutus', 'AboutController@index')->name('list');
            Route::post('/aboutus/store', 'AboutController@store')->name('store');
            Route::get('/aboutus/destroy/{id}', 'AboutController@destroy')->name('destroy');
        });


        //************ service admin *************
        Route::prefix('menu')->name('menu.')->group(function () {
            Route::get('/list', 'MenuController@index')->name('list');
            Route::post('/store', 'MenuController@store')->name('store');
            Route::get('/edit/{menu}', 'MenuController@edit')->name('edit');
            Route::post('/update/{menu}', 'MenuController@update')->name('update');
            Route::get('/destroy/{menu}', 'MenuController@destroy')->name('destroy');
        });

        //************ image admin *************
        Route::prefix('image')->name('image.')->group(function() {
            Route::get('list', 'ImageController@index')->name('list');
            Route::post('store', 'ImageController@store')->name('store');
            Route::get('edit/{image}', 'ImageController@edit')->name('edit');
            Route::post('update/{image}', 'ImageController@update')->name('update');
            Route::get('destroy/{image}', 'ImageController@destroy')->name('destroy');
        });


    });

// FILE MANAGER
Route::group(['prefix' => 'filemanager', 'middleware' => ['web', 'auth:admin']], function () {
    Lfm::routes();
});

app/Models/Setting.php
<?php

namespace App\Models;

use App\Traits\HasMeta;
use App\Traits\HasScope;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasScope,HasMeta;

    /**
     * @var array
     */
    protected $guarded = [];

    /**
     * @var array
     */
    protected $visible = [
        'key', 'value'
    ];

    /**
     * @var bool
     */
    public $timestamps = false;

    /**
     * @param  string $value
     *
     * @return  void
     */
    public function setKeyAttribute($value)
    {
        $this->attributes['key'] = \Str::slug($value, '_');
    }

    /**
     * @param  string $value
     *
     * @return  void
     */
    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = \Str::slug($value, ' ', '');
    }
}

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function edit()
    {

        $response = [];

        $response = $this->AdminVariable();

        $response['app_logo']=optional(Setting::firstWhere('key','app_logo'))->value;
        $response['app_tell']=optional(Setting::firstWhere('key','app_tell'))->value;
        $response['app_mobile']=optional(Setting::firstWhere('key','app_mobile'))->value;

        $response['app_name']=optional(Setting::firstWhere('key','app_name'))->value;
        $response['app_description']=optional(Setting::firstWhere('key','app_description'))->value;
        $response['app_slogan']=optional(Setting::firstWhere('key','app_slogan'))->value;
        $response['app_address']=optional(Setting::firstWhere('key','app_address'))->value;



        return view('admin.page.setting.setting',compact('response'));
    }

    public function update(Request $request)
    {

        // UPDATE LOGO TO STORAGE/SETTING
        if ($request->hasFile('photo')) {

            $image = $request->file('photo');
            $input['imagename'] = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('storage\setting');
//            $destinationPath = 'storage/setting';
            $img =\Intervention\Image\Facades\Image::make($image->getRealPath());
            $img->fit(200)->save($destinationPath. $input['imagename']);

            /* APP LOGO */
            $app_logo=Setting::firstWhere('key','app_logo');
            if ($app_logo!='')
            {
                $app_logo->value='storage/setting'.$input['imagename'];
            }
            else
            {
                $app_logo=new Setting([
                    'key'=>'app_logo',
                    'value'=>'storage/setting/'.$input['imagename'],
                    'title'=>'لوگو سایت',
                ]);
            }
            $app_logo->save();

            // UPDATE LOGO TO STORAGE/SETTING
        }


        /* Name */
        $this->updateSettingInfo('app_name',$request->title,'عنوان سایت');

        /* Issue */
        $this->updateSettingInfo('app_slogan',$request->slogan,'موضوع سایت');

        /* Address */
        $this->updateSettingInfo('app_address',$request->address,'آدرس سایت');

        /*  Tells and Mobiles */
        $this->updateSettingInfo('app_tell',$request->tell,'تلفن سایت');


        /*  Description */
        $this->updateSettingInfo('app_description',$request->description,'درباره ما');





        return redirect()->back()->with('ویرایش با موفقیت انجام شد');
    }

    public function updateSettingInfo($key,$title,$help)
    {
        $info   =   Setting::firstWhere( 'key' , $key );
        if ($info !== null)
        {
            $info->value  =  $title;
        }
        else
        {
            $info = new Setting();
            $info->key   = $key;
            $info->value = $title;
            $info->value = $help;
        }
        $info->save();

        return true;
    }
}

resources/views/admin/page/setting/setting.blade.php
@extends('admin.index')

@section('breadCrumb')
    {{ \DaveJamesMiller\Breadcrumbs\Facades\Breadcrumbs::render('admin.setting') }}
@endsection


@section('content')

    <section class="direction-ltr bg-white pt-0">
        <div class="container-fluid my-5">
            @include('message.message')
            <form action="{{route('admin.setting.update')}}" method="POST" enctype="multipart/form-data"
                  class="form admin-form">
            @csrf

                <div class="form-row mb-3 p-3">
                    <div class="align-right mr-2">
                        <div class="image-upload">
                            <label for="photo">
                                <span class="admin-input-label d-block">انتخاب تصویر</span>
                                <img src="{{isset($response['app_logo']) ? url( $response['app_logo']): url('/front/img/structure/image-add-button.png') }}" id="slideshowfileimg"
                                     class="img-thumbnail admin-form-img"/>
                            </label>
                            <input type="file" name="photo" id="photo" onchange="readURL(this);"
                                   class="d-none" value="{{isset($response['app_logo']) ? url( $response['app_logo']) : '' }}">
                        </div>
                    </div>
                </div>

                <div class="form-row mt-3">
                    <div class="col-md-12 mx-auto mb-4">
                        <label for="title" class="admin-input-label"><i
                                class="fas fa-pencil-alt prefix text-right"></i>&nbsp;عنوان مجموعه </label>
                        <input type="text" class="form-control  admin-input @error('title') is-invalid @enderror"
                               id="title" name="title" placeholder="عنوان مجموعه " autocomplete="off"
                               value="{{$response['app_name']!='' ? $response['app_name'] : ''}}">
                    </div>

                </div>

                <div class="form-row mt-3">
                    <div class="col-md-12 mx-auto mb-4">
                        <label for="slogan" class="admin-input-label"><i
                                class="fas fa-pencil-alt prefix text-right"></i>&nbsp;شعار مجموعه </label>
                        <input type="text" class="form-control  admin-input @error('slogan') is-invalid @enderror"
                               id="slogan" name="slogan" placeholder="شعار مجموعه " autocomplete="off"
                               value="{{$response['app_slogan']!='' ? $response['app_slogan'] : ''}}">
                    </div>
                </div>

                <div class="form-row mt-3">
                    <div class="col-md-12 mx-auto mb-4">
                        <label for="tell" class="admin-input-label"><i
                                class="fas fa-pencil-alt prefix text-right"></i>&nbsp; تلفن تماس
                            <span class="font-size-14 text-danger"> (با - از هم جدا کنید) </span>
                        </label>
                        <input type="text" class="form-control admin-input @error('tell') is-invalid @enderror"
                               id="tell" name="tell" placeholder="تلفن تماس" autocomplete="off"
                               value="{{$response['app_tell']!='' ? $response['app_tell'] : ''}}">
                    </div>
                </div>

                <div class="form-row mt-3">

                    <div class="col-md-12 mx-auto mb-4">
                        <label for="address" class="admin-input-label"><i
                                class="fas fa-pencil-alt prefix text-right"></i>&nbsp; آدرس </label>
                        <input type="text" class="form-control  admin-input @error('address') is-invalid @enderror"
                               id="address" name="address" placeholder="آدرس " autocomplete="off"
                               value="{{$response['app_address']!='' ? $response['app_address'] : ''}}">
                    </div>
                </div>


                <div class="form-row mt-3">
                    <div class="col-md-12 mx-auto mb-4">
                        <label for="description" class="admin-input-label"><i class="fas fa-pencil-alt prefix text-right"></i>&nbsp; توضیحات فوتر</label>
                        <textarea class="form-control admin-input-label p-2 content" id="description" name="description" placeholder="درباره ما">{{$response['app_description']}}</textarea>
                    </div>

                </div>

                <div class="form-row my-4">
                    <input type="submit"
                           class="col-xl-4 col-lg-4 col-md-8 col-sm-10 col-xs-10 btn admin-submit"
                           value="ثبت اطلاعات">
                </div>

            </form>
        </div>
    </section>

@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.9.11/tinymce.min.js"></script>
    <script>

        tiny();


        // **** TINY MCE
        function tiny() {
            var editor_config = {
                path_absolute: "/",
                selector: "textarea.content",
                directionality: 'rtl',
                height: '350px',
                plugins: [
                    "advlist autolink lists  charmap print preview hr anchor pagebreak",
                    "searchreplace wordcount visualblocks visualchars code fullscreen",
                    "insertdatetime  nonbreaking save table contextmenu directionality",
                    "emoticons template paste textcolor colorpicker textpattern link"
                ],//image media link
                toolbar: "insertfile undo redo | styleselect fontselect fontsizeselect forecolor  | bold italic | alignleft aligncenter alignright alignjustify | ltr rtl | bullist numlist outdent indent | link",
                fontsize_formats: "8px 9px 10px 11px 12px 14px 16px 18px 20px 22px 24px 36px",
                relative_urls: false,
                file_browser_callback: function (field_name, url, type, win) {
                    var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
                    var y = window.innerHeight || document.documentElement.clientHeight || document.getElementsByTagName('body')[0].clientHeight;

                    var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
                    if (type == 'image') {
                        cmsURL = cmsURL + "&type=Images";
                    } else {
                        cmsURL = cmsURL + "&type=Files";
                    }

                    tinyMCE.activeEditor.windowManager.open({
                        file: cmsURL,
                        title: 'Filemanager',
                        width: x * 0.8,
                        height: y * 0.8,
                        resizable: "yes",
                        close_previous: "no"
                    });
                }
            };
            tinymce.init(editor_config);
        }



        // **** PRIVIEW IMAGE
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#slideshowfileimg').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>

@endsection

resources/views/admin/page/setting/social.blade.php
@extends('admin.index')

@section('breadCrumb')
    {{ \DaveJamesMiller\Breadcrumbs\Facades\Breadcrumbs::render('admin.social') }}
@endsection

@section('content')
    @include('message.message')
    <div class="table-responsive admin-div-table">
        <table class="table table-striped">
            <tr class="admin-table-hr-row">
                <td class="admin-table-hr">شبکه اجتماعی</td>
                <td class="admin-table-hr">عنوان</td>
                <td class="admin-table-hr">لینک</td>
                <td class="admin-table-hr">حذف</td>
            </tr>
            <tbody>
            @foreach($response['socials'] as $social)
                <tr class="text-center font-size-14">
                    <td class="admin-danger">
                        @if($social->key==='telegram')
                            تلگرام
                        @elseif($social->key==='instagram')
                            اینستگرام
                        @elseif($social->key==='whatsapp')
                            واتس آپ
                        @elseif($social->key==='linkedin')
                            لینکدین
                        @elseif($social->key==='youtube')
                            واتس آپ
                        @elseif($social->key==='facebook')
                            فیسبوک
                        @elseif($social->key==='twitter')
                            توییتر
                        @endif
                    </td>
                    <td class="admin-info">{{$social->unique}}</td>
                    <td class="admin-black">{{$social->value}}</td>
                    <td>
                        <a href="{{route('admin.social.destroy',$social->id)}}" class="btn btn-outline-danger btn-sm font-yekan">
                            حذف
                        </a>
                    </td>

                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $response['socials']->links() }}
    </div>


    <section class="direction-ltr bg-white pt-0">
        <div class="container-fluid my-5">
            <form  action="{{route('admin.social.store')}}" method="POST" class="form admin-form">
                @csrf
                <div class="form-row mt-3">
                    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-xs-12 mx-auto mb-4">
                        <label for="type_id" class="admin-input-label"><i class="fas fa-pencil-alt prefix text-right"></i>&nbsp;نوع راه ارتباطی</label>
                        <select class="form-control admin-input" id="type_id" name="type">
                            <option value="telegram">تلگرام</option>
                            <option value="instagram">اینستگرام</option>
                            <option value="whatsapp">واتس اپ</option>
                            <option value="linkedin">لینکدین</option>
                            <option value="youtube">یوتوب</option>
                            <option value="facebook">فیسبوک</option>
                            <option value="twitter">توییتر</option>
                        </select>
                    </div>
                    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-xs-12 mx-auto mb-4">
                        <label for="title" class="admin-input-label"><i class="fas fa-pencil-alt prefix text-right"></i>&nbsp;عنوان</label>
                        <input class="form-control admin-input"  autocomplete="off" type="text" id="title" name="title" value="{{old('title')}}" placeholder="عنوان">
                    </div>
                    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-xs-12 mx-auto mb-4">
                        <label for="link_id" class="admin-input-label"><i class="fas fa-pencil-alt prefix text-right"></i>&nbsp;لینک ارتباطی</label>
                        <input class="form-control admin-input" autocomplete="off" type="text" id="link_id" name="link" value="{{old('link')}}" placeholder="لینک راه ارتباطی">
                    </div>

                </div>


                <div class="form-row my-4">
                    <input type="submit" class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12 btn admin-submit" value="افزودن">

                </div>
            </form>
        </div>
    </section>



@endsection